services:
  # ZooKeeper cluster
  zookeeper1:
    image: zookeeper:3.7
    container_name: zookeeper1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    ports:
      - "2181:2181"
    volumes:
      - zk1_data:/data
      - zk1_datalog:/datalog
    networks:
      - app-network

  zookeeper2:
    image: zookeeper:3.7
    container_name: zookeeper2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zk2_data:/data
      - zk2_datalog:/datalog
    networks:
      - app-network

  zookeeper3:
    image: zookeeper:3.7
    container_name: zookeeper3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zk3_data:/data
      - zk3_datalog:/datalog
    networks:
      - app-network

  # JournalNode cluster
  journalnode1:
    image: apache/hadoop:3.3.6
    container_name: journalnode1
    command: ["tail", "-f", "/dev/null"]
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - jn1_data:/hadoop/dfs/journal
    networks:
      - app-network

  journalnode2:
    image: apache/hadoop:3.3.6
    container_name: journalnode2
    command: ["tail", "-f", "/dev/null"]
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - jn2_data:/hadoop/dfs/journal
    networks:
      - app-network

  journalnode3:
    image: apache/hadoop:3.3.6
    container_name: journalnode3
    command: ["tail", "-f", "/dev/null"]
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - jn3_data:/hadoop/dfs/journal
    networks:
      - app-network

  # NameNode
  namenode1:
    image: apache/hadoop:3.3.6
    container_name: namenode1
    command: ["tail", "-f", "/dev/null"]
    environment:
      - HADOOP_HOME=/opt/hadoop
    ports:
      - "9820:9820"  # RPC
      - "9870:9870"  # Web UI
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - nn1_data:/hadoop/dfs/name
    networks:
      - app-network

  namenode2:
    image: apache/hadoop:3.3.6
    container_name: namenode2
    command: ["tail", "-f", "/dev/null"]
    environment:
      - HADOOP_HOME=/opt/hadoop
    ports:
      - "9821:9820"  # RPC
      - "9871:9870"  # Web UI
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - nn2_data:/hadoop/dfs/name
    networks:
      - app-network

  # DataNode
  datanode1:
    image: apache/hadoop:3.3.6
    container_name: datanode1
    hostname: datanode1
    command: ["tail", "-f", "/dev/null"]
    environment:
      - HADOOP_HOME=/opt/hadoop
      - DATANODE_HOSTNAME=datanode1
    ports:
      - "9866:9866"  # Data transfer
      - "9864:9864"  # Web UI
      - "9867:9867"  # IPC
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - dn1_data:/hadoop/dfs/data
    networks:
      - app-network

  datanode2:
    image: apache/hadoop:3.3.6
    container_name: datanode2
    hostname: datanode2
    command: ["tail", "-f", "/dev/null"]
    environment:
      - HADOOP_HOME=/opt/hadoop
      - DATANODE_HOSTNAME=datanode2
    ports:
      - "9876:9866"  # Data transfer
      - "9874:9864"  # Web UI
      - "9877:9867"  # IPC
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - dn2_data:/hadoop/dfs/data
    networks:
      - app-network

  datanode3:
    image: apache/hadoop:3.3.6
    container_name: datanode3
    hostname: datanode3
    command: ["tail", "-f", "/dev/null"]
    environment:
      - HADOOP_HOME=/opt/hadoop
      - DATANODE_HOSTNAME=datanode3
    ports:
      - "9886:9866"  # Data transfer
      - "9884:9864"  # Web UI
      - "9887:9867"  # IPC
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - dn3_data:/hadoop/dfs/data
    networks:
      - app-network

  # ResourceManager
  resourcemanager1:
    image: apache/hadoop:3.3.6
    container_name: resourcemanager1
    command: ["tail", "-f", "/dev/null"]
    environment:
      - HADOOP_HOME=/opt/hadoop
    ports:
      - "8030:8030"  # ResourceManager RPC
      - "8088:8088"  # ResourceManager Web UI
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
    networks:
      - app-network

  resourcemanager2:
    image: apache/hadoop:3.3.6
    container_name: resourcemanager2
    command: ["tail", "-f", "/dev/null"]
    environment:
      - HADOOP_HOME=/opt/hadoop
    ports:
      - "8031:8030"  # ResourceManager RPC
      - "8089:8088"  # ResourceManager Web UI
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
    networks:
      - app-network

volumes:
  zk1_data:
  zk1_datalog:
  zk2_data:
  zk2_datalog:
  zk3_data:
  zk3_datalog:
  jn1_data:
  jn2_data:
  jn3_data:
  nn1_data:
  nn2_data:
  dn1_data:
  dn2_data:
  dn3_data:

networks:
  app-network:
    external: true
    name: share-enterprise-ci